// End-to-end test of api/stripe-webhook.js with a REAL Stripe signature.
//
// This is the code path that silently broke every payment before: Vercel was
// still parsing the body, so the bytes Stripe signed were not the bytes we
// verified. Here the request is a real stream of raw bytes, exactly as Vercel
// delivers it when bodyParser is off, and the signature is generated by the
// Stripe library itself.
const path = require("path");
const { Readable } = require("stream");
const Stripe = require("stripe");

const SECRET = "whsec_testsecretfortestingonly0000000000";
process.env.STRIPE_SECRET_KEY = "sk_test_dummy";
process.env.STRIPE_WEBHOOK_SECRET = SECRET;
process.env.SUPABASE_URL = "https://example.supabase.co";
process.env.SUPABASE_SERVICE_ROLE_KEY = "dummy";

// ---- stub @supabase/supabase-js before the handler requires it ----
const supabasePath = require.resolve("@supabase/supabase-js");
let db; // per-test state

function makeStubClient() {
  return {
    from(table) {
      const q = {
        _table: table,
        select() { return q; },
        eq(col, val) { q._eqVal = val; return q; },
        async maybeSingle() {
          db.calls.push(`select ${q._table}`);
          if (q._table === "webhook_events") {
            return { data: db.seenEvents.has(q._eqVal) ? { stripe_event_id: q._eqVal } : null, error: null };
          }
          return { data: null, error: null };
        },
        async upsert(row) {
          db.calls.push(`upsert ${q._table} ${row.status || ""}`.trim());
          db.upserts.push({ table: q._table, row });
          if (q._table === "payments" && db.failPayment) {
            return { error: { code: "XX000", message: "simulated payments write failure" } };
          }
          return { error: null };
        },
        async insert(row) {
          db.calls.push(`insert ${q._table}`);
          if (q._table === "webhook_events") {
            if (db.failMark) return { error: { code: "XX000", message: "simulated transient failure" } };
            db.seenEvents.add(row.stripe_event_id);
          }
          return { error: null };
        }
      };
      return q;
    },
    async rpc(name, args) {
      db.calls.push(`rpc ${name}`);
      db.rpcCalls.push(args);
      if (db.failRpc) return { error: { message: "simulated rpc failure" } };
      return { error: null };
    }
  };
}
require.cache[supabasePath] = {
  id: supabasePath, filename: supabasePath, loaded: true, exports: { createClient: makeStubClient }
};

const handler = require("../api/stripe-webhook.js");

function makeReq(rawBody, signature) {
  const req = Readable.from([Buffer.from(rawBody)]);
  req.method = "POST";
  req.headers = { "stripe-signature": signature };
  return req;
}
function makeRes() {
  const res = { statusCode: null, body: null, _sent: null };
  res.status = (c) => { res.statusCode = c; return res; };
  res.json = (o) => { res.body = o; return res; };
  res.send = (s) => { res._sent = s; return res; };
  return res;
}

function buildEvent(id, sessionId, amount) {
  return JSON.stringify({
    id, object: "event", type: "checkout.session.completed",
    data: { object: {
      id: sessionId, object: "checkout_session",
      metadata: { slug: "ruta77", amount: String(amount), name: "Ruta77",
                  place: "北軽井沢", image_url: "", website_url: "https://www.ruta77studio.com" }
    } }
  });
}

function sign(payload) {
  return Stripe.webhooks.generateTestHeaderString({ payload, secret: SECRET });
}

function reset(extra = {}) {
  db = { calls: [], upserts: [], rpcCalls: [], seenEvents: new Set(),
         failRpc: false, failMark: false, ...extra };
}

let pass = 0, fail = 0;
function check(label, cond, detail = "") {
  if (cond) { pass++; console.log(`   ✅ ${label}`); }
  else { fail++; console.log(`   ❌ ${label} ${detail}`); }
}

(async () => {
  // 1) Happy path with a genuine signature over the exact raw bytes.
  console.log("\n1) Firma válida sobre los bytes crudos exactos");
  reset();
  let payload = buildEvent("evt_1", "cs_test_1", 500);
  let res = makeRes();
  await handler(makeReq(payload, sign(payload)), res);
  check("responde 200", res.statusCode === 200, `(fue ${res.statusCode})`);
  check("llama a apply_paid_listing una vez", db.rpcCalls.length === 1);
  check("pasa el importe correcto", db.rpcCalls[0] && db.rpcCalls[0].p_amount === 500,
        JSON.stringify(db.rpcCalls[0]));
  check("pasa el slug correcto", db.rpcCalls[0] && db.rpcCalls[0].p_slug === "ruta77");
  check("marca el pago como completed",
        db.upserts.some((u) => u.table === "payments" && u.row.status === "completed"));
  check("registra el evento DESPUÉS de aplicar el pago",
        db.calls.indexOf("rpc apply_paid_listing") < db.calls.indexOf("insert webhook_events"),
        db.calls.join(" → "));

  // 2) Tampered body — the exact attack the signature exists to stop.
  console.log("\n2) Cuerpo manipulado tras la firma (importe cambiado a 999999)");
  reset();
  const original = buildEvent("evt_2", "cs_test_2", 500);
  const goodSig = sign(original);
  const tampered = original.replace('"amount":"500"', '"amount":"999999"');
  res = makeRes();
  await handler(makeReq(tampered, goodSig), res);
  check("rechaza con 400", res.statusCode === 400, `(fue ${res.statusCode})`);
  check("NO toca la base de datos", db.rpcCalls.length === 0);

  // 3) Duplicate delivery of an event already recorded.
  console.log("\n3) Entrega duplicada de un evento ya registrado");
  reset();
  db.seenEvents.add("evt_3");
  payload = buildEvent("evt_3", "cs_test_3", 500);
  res = makeRes();
  await handler(makeReq(payload, sign(payload)), res);
  check("responde 200", res.statusCode === 200);
  check("marcado como duplicate", res.body && res.body.duplicate === true);
  check("NO vuelve a aplicar el pago", db.rpcCalls.length === 0);

  // 4) The RPC itself fails — Stripe must be told to retry, and the event
  //    must NOT be recorded as processed.
  console.log("\n4) Fallo del RPC (la BD rechaza la operación)");
  reset({ failRpc: true });
  payload = buildEvent("evt_4", "cs_test_4", 500);
  res = makeRes();
  await handler(makeReq(payload, sign(payload)), res);
  check("responde 500 para que Stripe reintente", res.statusCode === 500, `(fue ${res.statusCode})`);
  check("NO marca el evento como procesado", !db.seenEvents.has("evt_4"),
        "un pago se perdería para siempre");

  // 5) The RPC succeeds but recording the event fails — Stripe retries, and
  //    the DB-level idempotency (added in supabase-schema.sql) is what stops
  //    the retry from double-counting.
  console.log("\n5) RPC OK pero falla el registro del evento → Stripe reintenta");
  reset({ failMark: true });
  payload = buildEvent("evt_5", "cs_test_5", 500);
  res = makeRes();
  await handler(makeReq(payload, sign(payload)), res);
  check("responde 500 (reintento)", res.statusCode === 500, `(fue ${res.statusCode})`);
  check("el pago sí se aplicó una vez", db.rpcCalls.length === 1);
  console.log("      ↳ el reintento volverá a llamar al RPC con el mismo");
  console.log("        stripe_session_id; apply_paid_listing lo detecta y no");
  console.log("        vuelve a sumar (verificado contra Postgres real).");

  // 6) The payments row is what makes applying idempotent — if writing it
  //    fails, the payment must NOT be applied, or a retry would double it.
  console.log("\n6) Falla el registro del pago → NO se debe aplicar el importe");
  reset({ failPayment: true });
  payload = buildEvent("evt_6", "cs_test_6", 500);
  res = makeRes();
  await handler(makeReq(payload, sign(payload)), res);
  check("responde 500 para que Stripe reintente", res.statusCode === 500, `(fue ${res.statusCode})`);
  check("NO aplica el pago al ranking", db.rpcCalls.length === 0,
        "se habría sumado sin poder detectar el reintento");
  check("NO marca el evento como procesado", !db.seenEvents.has("evt_6"));

  // 7) Wrong HTTP method.
  console.log("\n7) Método incorrecto (GET)");
  reset();
  res = makeRes();
  const getReq = Readable.from([Buffer.from("")]);
  getReq.method = "GET"; getReq.headers = {};
  await handler(getReq, res);
  check("responde 405", res.statusCode === 405, `(fue ${res.statusCode})`);

  // 7) The config that broke everything before.
  console.log("\n8) La config que antes se perdía silenciosamente");
  check("bodyParser está desactivado en el handler exportado",
        handler.config && handler.config.api && handler.config.api.bodyParser === false,
        JSON.stringify(handler.config));

  console.log(`\n──────────────\n${pass} pasaron, ${fail} fallaron`);
  process.exit(fail ? 1 : 0);
})();
